/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-11-09 02:28:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.gym;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/user/login.jsp", Long.valueOf(1667822192065L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/Documents/develop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH-semi-project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667273598260L));
    _jspx_dependants.put("/layout/header.jsp", Long.valueOf(1667960874842L));
    _jspx_dependants.put("/user/signup.jsp", Long.valueOf(1667960848284L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>피트니즈 - Fitneeds</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resource/fitneeds.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- fontawesome -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- google font -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- font-family: 'Noto Sans KR', sans-serif; -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap - icon -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap - css -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- fontawesome - icon  -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Radar Chart -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- daum zipcode -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<!-- kakaomaps - ykm -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=b70a07e8ebffe5918d15f49ba310485f&libraries=services\"></script>\r\n");
      out.write("<!-- kakaomaps - kms -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=12fd95dff1fb7039a62aa4e24d3011f0&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- AOS -->\r\n");
      out.write("<link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- owl carousel -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- sweetalert -->\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/base.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/index.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/search.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/gym-detail.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/users-mypage.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/users.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bs.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/host-user.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/host-bsuser.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bs-page.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Site header -->\r\n");
      out.write("	<header id=\"header\">\r\n");
      out.write("		<div class=\"containerbox\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"float-start\">\r\n");
      out.write("				<h1 id=\"header_logo\">\r\n");
      out.write("					<a class=\"header_a_tag\" href=\"/\">Fitneeds</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"float-start\">\r\n");
      out.write("				<nav id=\"header_nav_text\">\r\n");
      out.write("					<ul id=\"header_nav_menu\">\r\n");
      out.write("						<li class=\"float-start\"><a class=\"header_a_tag\"\r\n");
      out.write("							href=\"/main.search\">헬스장검색</a></li>\r\n");
      out.write("						<li class=\"float-start\"><a class=\"header_a_tag\" href=\"#\">실시간리뷰</a></li>\r\n");
      out.write("						<li class=\"float-start\"><a class=\"header_a_tag\" href=\"#\">운동기록</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul id=\"header_nav_person\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- 로그인 Modal -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"loginModal\" class=\"loginModal-overlay\" align=\"center\">\r\n");
      out.write("	<div class=\"window\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-12 text-end close-area\" onclick=hideLoginModal()>\r\n");
      out.write("			<a><i class=\"fa-solid fa-x\" style=\"color: #808080\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"text_title title\">회원 로그인</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 폼 -->\r\n");
      out.write("		<form id=\"form_login\">\r\n");
      out.write("			<div class=\"row justify-content-center mt-3\">\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">이메일</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"login_id\" id=\"login_id\"\r\n");
      out.write("						placeholder=\"이메일을 입력하세요.\" maxlength=\"40\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">비밀번호</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"login_pw\" id=\"login_pw\"\r\n");
      out.write("						placeholder=\"비밀번호를 입력하세요.\" maxlength=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<button type=\"button\" class=\"btn_base\" id=\"btn_login\">로그인</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-1\">\r\n");
      out.write("					<input class=\"form-check-input\" type=\"checkbox\" id=\"login_bs\">\r\n");
      out.write("					<label class=\"form-check-label\" for=\"login_bs\"\r\n");
      out.write("						style=\"color: #404040; font-size: 14px; letter-spacing: -1px;\">사업자\r\n");
      out.write("						로그인</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-4\" style=\"letter-spacing: -1px;\">\r\n");
      out.write("					<span style=\"color: #404040;\">계정이 없으신가요?</span> <a href=\"#\"\r\n");
      out.write("						onclick=\"showSignupModal(); return false;\">회원가입</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-1\"\r\n");
      out.write("					style=\"color: #808080; font-size: small; letter-spacing: -1px;\">\r\n");
      out.write("					<a onclick=\"showSearchPw()\">비밀번호를 잊으셨나요?</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- 비밀번호 찾기 폼 -->\r\n");
      out.write("		<form class=\"search\" id=\"form_searchPw\">\r\n");
      out.write("			<div class=\"row justify-content-center mt-4\">\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<input type=\"text\" name=\"email\" id=\"searchPw_email\"\r\n");
      out.write("						placeholder=\"이메일\" maxlength=\"40\">\r\n");
      out.write("					<div class=\"text-start mt-1 mb-1\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">회원 가입시 사용한\r\n");
      out.write("							이메일을 입력하세요.</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<input type=\"text\" name=\"phone\" id=\"searchPw_phone\"\r\n");
      out.write("						placeholder=\"핸드폰 번호\" maxlength=\"14\">\r\n");
      out.write("					<div class=\"text-start mt-1 mb-1\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">회원 가입시 사용한\r\n");
      out.write("							핸드폰 번호를 입력하세요.</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<button class=\"btn_base\" type=\"button\" id=\"btn_search\">찾기</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-1\">\r\n");
      out.write("					<input class=\"form-check-input\" type=\"checkbox\" id=\"searchPw_bs\">\r\n");
      out.write("					<label class=\"form-check-label\" for=\"searchPw_bs\"\r\n");
      out.write("						style=\"color: #404040; font-size: 14px; letter-spacing: -1px;\">사업자 입니다.</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<a style=\"color: #808080\" onclick=\"toBackward()\">Back</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("			// 로그인 loginModal 열기\r\n");
      out.write("			function showLoginModal() {\r\n");
      out.write("				$(\"#loginModal\").attr(\"style\", \"display:inline-flex\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 로그인 loginModal 닫기\r\n");
      out.write("			function hideLoginModal() {\r\n");
      out.write("				$(\"#loginModal\").attr(\"style\", \"display:none\");\r\n");
      out.write("				toBackward();\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 비밀번호 찾기 페이지 처리\r\n");
      out.write("			function showSearchPw() {\r\n");
      out.write("				$(\"#form_login\").attr(\"style\", \"display:none\");\r\n");
      out.write("				$(\"#form_searchPw\").attr(\"style\", \"display:inline\");\r\n");
      out.write("				$(\"#loginModal .title\").text(\"비밀번호 찾기\");\r\n");
      out.write("				$(\"#loginModal .window\").attr(\"style\", \"height:450px\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 뒤로가기 처리\r\n");
      out.write("			function toBackward() {\r\n");
      out.write("				$(\".search\").attr(\"style\", \"display:none\");\r\n");
      out.write("				$(\"#loginModal input:not([type='checkbox']\").val(\"\");\r\n");
      out.write("				$(\"#form_login\").attr(\"style\", \"display:inline\");\r\n");
      out.write("				$(\"#loginModal .title\").text(\"회원 로그인\");\r\n");
      out.write("				$(\"#loginModal .window\").attr(\"style\", \"height:475px\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 떨림 애니메이션\r\n");
      out.write("			function wobble(element) {\r\n");
      out.write("				let order = [0, -8, 8, -4, 4, -2, 2, -1, 1, 0];\r\n");
      out.write("				let seq = [];\r\n");
      out.write("				order.forEach(function (y) { seq.push({ transform: \"translate(0,\" + y + \"px)\" }); });\r\n");
      out.write("				element.animate(seq, { duration: 300 });\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 유효성 검사 (공백 확인)\r\n");
      out.write("			function isFilled(elements) {\r\n");
      out.write("				for (i = 0; i < elements.length; i++) {\r\n");
      out.write("					if(elements[i].value == \"\") { \r\n");
      out.write("						wobble(elements[i]);\r\n");
      out.write("						elements[i].focus();\r\n");
      out.write("						return false; \r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				return true;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 로그인 함수\r\n");
      out.write("			function tryLogin() {\r\n");
      out.write("				$.post($(\"#login_bs\").is(\":checked\") ? \"/login.bs\" : \"/login.user\", $(\"#form_login\").serialize())\r\n");
      out.write("					.done((res) => {\r\n");
      out.write("						if (res == \"true\") {\r\n");
      out.write("							Swal.fire({ title: \"Success!\", icon: \"success\", text: \"로그인에 성공했습니다.\" })\r\n");
      out.write("								.then((result) => {\r\n");
      out.write("									if (result.isConfirmed) { location.reload(); }\r\n");
      out.write("								});\r\n");
      out.write("						} else {\r\n");
      out.write("							Swal.fire({ title: \"Error\", icon: \"error\", text: \"ID가 등록되지 않았거나 비밀번호가 올바르지 않습니다.\" });\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 비밀번호 찾기 함수\r\n");
      out.write("			function trySearchPw() {\r\n");
      out.write("				$.get($(\"#searchPw_bs\").is(\":checked\") ? \"/searchPw.bs\" : \"/searchPw.user\", $(\"#form_searchPw\").serialize())\r\n");
      out.write("				.done((res => {\r\n");
      out.write("						if (res == \"true\") {\r\n");
      out.write("							// Fake Alert\r\n");
      out.write("							Swal.fire({ title: \"Success!\", icon: \"success\", html: \"등록된 이메일 주소로<br>비밀번호 설정 링크가 발송되었습니다.<br>\" })\r\n");
      out.write("						} else {	\r\n");
      out.write("							Swal.fire({ title: \"Error\", icon: \"error\", text: \"등록된 가입 정보가 없습니다.\" });\r\n");
      out.write("						}\r\n");
      out.write("					}));\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// ESC 누르면 Modal 닫기\r\n");
      out.write("			$(window).on(\"keyup\", e => {\r\n");
      out.write("				if ($(\"#loginModal\")[0].style.display == \"inline-flex\" && e.keyCode == 27) { hideLoginModal(); }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 창 바깥쪽 클릭하면 Modal 닫기\r\n");
      out.write("			// $(\"#loginModal\").on(\"click\", e => {\r\n");
      out.write("			// 	if (e.target.classList.contains(\"loginModal-overlay\")) { hideLoginModal(); }\r\n");
      out.write("			// });\r\n");
      out.write("\r\n");
      out.write("			// 버튼 이벤트\r\n");
      out.write("			$(\"#btn_login\").on(\"click\", () => {\r\n");
      out.write("				if (isFilled($(\"#login_id, #login_pw\"))) { tryLogin(); }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#btn_search\").on(\"click\", () => {\r\n");
      out.write("				if (isFilled($(\"#searchPw_email, #searchPw_phone\"))) { trySearchPw(); }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 엔터 = 버튼 클릭\r\n");
      out.write("			$(\"#login_id, #login_pw\").on(\"keyup\", (e) => { if (e.keyCode == 13) { $(\"#btn_login\").click() } });\r\n");
      out.write("			$(\"#searchPw_email, #searchPw_phone\").on(\"keyup\", (e) => { if (e.keyCode == 13) { $(\"#btn_search\").click() } });;\r\n");
      out.write("		</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 회원가입 Modal -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"signupModal\" class=\"signupModal-overlay\" align=\"center\">\r\n");
      out.write("	<div class=\"window\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-12 text-end close-area\" onclick=hideSignupModal()>\r\n");
      out.write("			<a><i class=\"fa-solid fa-x\" style=\"color: #808080\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"text_title title\">일반 회원가입</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 회원가입 폼 -->\r\n");
      out.write("		<form id=\"form_sign\" method=\"post\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">이메일</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"users_email\" id=\"users_email\"\r\n");
      out.write("						placeholder=\"이메일을 입력하세요.\" maxlength=\"25\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-2\">\r\n");
      out.write("					<div class=\"error_msg text_mini text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span class=\"error_msg_display\" id=\"users_email_msg\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">비밀번호</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"users_pw\" id=\"users_pw\"\r\n");
      out.write("						placeholder=\"비밀번호를 입력하세요.\" maxlength=\"16\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">비밀번호 확인</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"users_pw_re\" id=\"users_pw_re\"\r\n");
      out.write("						placeholder=\"동일 비밀번호를 입력하세요.\" maxlength=\"16\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-2\">\r\n");
      out.write("					<div class=\"error_msg text_mini text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span class=\"error_msg_display\" id=\"users_pw_re_msg\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">연락처</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"users_phone\" id=\"users_phone\"\r\n");
      out.write("						placeholder=\"연락처를 입력하세요.\" maxlength=\"11\" oninput=validNum()>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-2\">\r\n");
      out.write("					<div class=\"error_msg text_mini text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span class=\"error_msg_display\" id=\"users_phone_msg\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<button type=\"button\" class=\"btn_base\" id=\"btn_sign\">회원가입</button>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\"\r\n");
      out.write("					style=\"font-size: small; letter-spacing: -1px;\">\r\n");
      out.write("					<span style=\"color: #808080;\">시설운영자로 가입하길 원하시나요?</span><br> <a\r\n");
      out.write("						href=\"/sign.bs\">사업자회원가입</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("        // 회원가입 signupModal 열기\r\n");
      out.write("        function showSignupModal() {\r\n");
      out.write("            $(\"#signupModal\").attr(\"style\", \"display:inline-flex\");\r\n");
      out.write("            $(\"#loginModal\").attr(\"style\", \"display:none\");\r\n");
      out.write("            toBackward();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("     	// 회원가입 signupModal 닫기\r\n");
      out.write("		function hideSignupModal() {\r\n");
      out.write("			$(\"#signupModal\").attr(\"style\", \"display:none\");\r\n");
      out.write("			\r\n");
      out.write("        	$(\"#users_email\").val(\"\");\r\n");
      out.write("        	$(\"#users_pw\").val(\"\");\r\n");
      out.write("        	$(\"#users_pw_re\").val(\"\");\r\n");
      out.write("        	$(\"#users_phone\").val(\"\");\r\n");
      out.write("        	\r\n");
      out.write("        	$(\"#users_email_msg\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#users_email_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("            $(\"#users_email_msg\").html(\"이메일 형식을 아이디로 사용합니다\");\r\n");
      out.write("\r\n");
      out.write("            $(\"#users_pw_re_msg\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#users_pw_re_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("            $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("            \r\n");
      out.write("            $(\"#users_phone_msg\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#users_phone_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("            $(\"#users_phone_msg\").html(\"연락처는 - 를 제외한 숫자만 입력해주세요\");\r\n");
      out.write("		}\r\n");
      out.write("     	\r\n");
      out.write("        // ESC 누르면 signupModal 닫기\r\n");
      out.write("        $(window).on(\"keyup\", e => {\r\n");
      out.write("            if ($(\"#signupModal\")[0].style.display == \"inline-flex\" && e.keyCode == 27) { hideSignupModal(); }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //  회원가입 함수\r\n");
      out.write("        function trySign() {\r\n");
      out.write("        	$.post(\"/sign.user\", $(\"#form_sign\").serialize())\r\n");
      out.write("                .done((resp) => {\r\n");
      out.write("                	if (resp == \"1\") {\r\n");
      out.write("                        Swal.fire({ title: \"Success!\", icon: \"success\", text: \"회원가입이 되었습니다.\"})\r\n");
      out.write("                            .then((result) => {\r\n");
      out.write("                                if (result.isConfirmed) { location.reload(); }\r\n");
      out.write("                            });\r\n");
      out.write("                    } else {\r\n");
      out.write("                        Swal.fire({ title: \"Error\", icon: \"error\", text: \"오류입니다. 관리자에게 문의해주세요.\"});\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("             	            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 회원가입 버튼 이벤트\r\n");
      out.write("        $(\"#btn_sign\").on(\"click\", () => {\r\n");
      out.write("            \r\n");
      out.write("            if ($(\"#users_email_msg\").css(\"color\") == \"rgb(255, 0, 0)\") { wobble($(\"#users_email\")[0]); $(\"#users_email\").focus(); }\r\n");
      out.write("            \r\n");
      out.write("            else if ($(\"#users_pw_re_msg\").css(\"color\") == \"rgb(255, 0, 0)\") {\r\n");
      out.write("                if ($(\"#users_pw_re_msg\").html() == \"특수문자를 포함한 8~16자리 입력해주세요\") { wobble($(\"#users_pw\")[0]); $(\"#users_pw\").focus(); }\r\n");
      out.write("                else if ($(\"#users_pw_re_msg\").html() == \"동일한 비밀번호를 입력해주세요\") { wobble($(\"#users_pw_re\")[0]); $(\"#users_pw_re\").focus(); }\r\n");
      out.write("            }\r\n");
      out.write("            else if ($(\"#users_phone_msg\").css(\"color\") == \"rgb(255, 0, 0)\") { \r\n");
      out.write("            	console.log($(\"#users_phone_msg\").css(\"color\"));\r\n");
      out.write("            	wobble($(\"#users_phone\")[0]); $(\"#users_phone\").focus();\r\n");
      out.write("            	\r\n");
      out.write("            } else {\r\n");
      out.write("            	if (isFilled($(\"#users_email, #users_pw, #users_pw_re, #users_phone\"))) { trySign(); }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 유효성 검사 Regex\r\n");
      out.write("        let emailRegex = /^[a-zA-Z0-9+-\\_.]{1,20}@[a-zA-Z0-9-]{1,15}\\.[a-zA-Z-.]{1,12}$/;\r\n");
      out.write("        let pwRegex = /^(?=.*[A-Za-z\\d])(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$/;\r\n");
      out.write("        let phoneRegex = /^0[\\d]{8,10}$/;\r\n");
      out.write("\r\n");
      out.write("        // input 칸에 숫자 외에 입력 안되게 막기\r\n");
      out.write("        function validNum() {\r\n");
      out.write("            event.target.value = event.target.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("        // 이메일(아이디) - 아이디 중복검사 & 값 입력 유효성 검사 display\r\n");
      out.write("\r\n");
      out.write("        function idEvent() {\r\n");
      out.write("            if ($(\"#users_email\").val() == \"\") {\r\n");
      out.write("                $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_email_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                $(\"#users_email_msg\").html(\"이메일 형식을 아이디로 사용합니다\");\r\n");
      out.write("            } else if (!emailRegex.test($(\"#users_email\").val())) {\r\n");
      out.write("                $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_email_msg\").css(\"color\", \"red\");\r\n");
      out.write("                $(\"#users_email_msg\").html(\"이메일 형식을 확인해주세요\");\r\n");
      out.write("            } else {\r\n");
      out.write("            	let email = $(\"#users_email\").val();\r\n");
      out.write("            	\r\n");
      out.write("            	$.ajax({\r\n");
      out.write("                    url: \"/duplCheck.user\",\r\n");
      out.write("                    data: { \"users_email\": email }\r\n");
      out.write("                }).done(function (resp) {\r\n");
      out.write("                	\r\n");
      out.write("                    console.log(resp);\r\n");
      out.write("                    if (resp == \"true\") { // 아이디가 이미 존재하므로 사용할 수 없는 경우\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"color\", \"red\");\r\n");
      out.write("                        $(\"#users_email_msg\").html(\"이미 사용 중인 ID 입니다.\");\r\n");
      out.write("                    } else { // 아이디가 존재하지않으므로 사용할 수 있는 경우\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                        $(\"#users_email_msg\").html(\"사용 가능한 ID 입니다.\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        $(\"#users_email\").on(\"focus\", function () {\r\n");
      out.write("            idEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_email\").on(\"keyup\", function () {\r\n");
      out.write("            idEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 패스워드 - 값 입력 유효성 검사 display\r\n");
      out.write("\r\n");
      out.write("        function pwEvent() {\r\n");
      out.write("            if ($(\"#users_pw, #users_pw_re\").val() == \"\") {\r\n");
      out.write("                $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_pw_re_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("\r\n");
      out.write("                if (!pwRegex.test($(\"#users_pw\").val())) {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                } else if (($(\"#users_pw\").val() != $(\"#users_pw_re\").val()) && $(\"#users_pw, #users_pw_re\").val() != \"\") {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"동일한 비밀번호를 입력해주세요\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                } else if (($(\"#users_pw\").val() != $(\"#users_pw_re\").val()) && $(\"#users_pw, #users_pw_re\").val() == \"\") {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"위에 입력한 비밀번호와 일치하지않습니다\");\r\n");
      out.write("\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"none\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_pw, #users_pw_re\").on(\"focus\", function () {\r\n");
      out.write("            pwEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_pw, #users_pw_re\").on(\"keyup\", function () {\r\n");
      out.write("            pwEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 전화번호 - 값 입력 유효성 검사 display\r\n");
      out.write("\r\n");
      out.write("        function phoneEvent() {\r\n");
      out.write("            if ($(\"#users_phone\").val() == \"\") {\r\n");
      out.write("                $(\"#users_phone_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_phone_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                $(\"#users_phone_msg\").html(\"연락처는 - 를 제외한 숫자만 입력해주세요\");\r\n");
      out.write("            } else {\r\n");
      out.write("            	if (!phoneRegex.test($(\"#users_phone\").val())) {\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_phone_msg\").html(\"옳바른 번호 형식을 입력해주세요\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"display\", \"none\");\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                    $(\"#users_phone_msg\").html(\"연락처는 - 를 제외한 숫자만 입력해주세요\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_phone\").on(\"focus\", function () {\r\n");
      out.write("            phoneEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_phone\").on(\"keyup\", function () {\r\n");
      out.write("            phoneEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 엔터 = 버튼 클릭\r\n");
      out.write("        $(\"#users_email, #users_pw, #users_pw_re, #users_phone\").on(\"keyup\", (e) => { if (e.keyCode == 13) { $(\"#btn_sign\").click() } });\r\n");
      out.write("\r\n");
      out.write("    </script>");
      out.write("\r\n");
      out.write("<!-- Search main -->\r\n");
      out.write("<main id=\"search\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div id=\"map\">\r\n");
      out.write("			<!-- 메인 검색창 -->\r\n");
      out.write("			<form onsubmit=\"searchPlaces(); return false;\" id=\"mainForm\">\r\n");
      out.write("				<div class=\"search_main\">\r\n");
      out.write("					<div class=\"search_main_span\">\r\n");
      out.write("						<span style=\"font-weight: 100;\">Your</span> \r\n");
      out.write("						<span style=\"font-weight: 700;\">Needs</span>\r\n");
      out.write("						<span style=\"font-weight: 100;\">For</span> \r\n");
      out.write("						<span style=\"font-weight: 700;\">Fitness</span>\r\n");
      out.write("					</div>\r\n");
      out.write("						<div class=\"search_main_input\">\r\n");
      out.write("							<input type=\"text\" id=\"keyword\"\r\n");
      out.write("								placeholder=\"지역명 또는 헬스장명을 검색해보세요.\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_main_icon\">\r\n");
      out.write("							<i id=\"searchBtn\" class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<script>\r\n");
      out.write("							$(\"#keyword\").on(\"keyup\", function(e){\r\n");
      out.write("								if(e.keyCode == 13) {\r\n");
      out.write("									$(\"#mainForm\").submit();\r\n");
      out.write("								};\r\n");
      out.write("							});\r\n");
      out.write("						</script>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<!-- 검색 리스트 네비 -->\r\n");
      out.write("			<div class=\"searchListNav\">\r\n");
      out.write("				<form action=\"/gym.search\" id=\"subForm\">\r\n");
      out.write("					<div class=\"search_sub\">\r\n");
      out.write("						<div class=\"search_sub_input\">\r\n");
      out.write("							<input type=\"text\" id=\"searchInput\" name=\"searchInput\" \r\n");
      out.write("								placeholder=\"지역명 또는 헬스장명을 검색해보세요.\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_sub_icon\">\r\n");
      out.write("							<i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"search_sub_filter\">\r\n");
      out.write("						<div class=\"search_tag_icon\" style=\"margin-left: 37px;\">\r\n");
      out.write("							<img src=\"/resource/filter.png\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_tag\" style=\"margin-left: 5px;\">\r\n");
      out.write("							<label for=\"\" class=\"filter_open filter\">#24시간</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_tag\" style=\"margin-left: 5px;\">\r\n");
      out.write("							<label for=\"\" class=\"filter_locker filter\">#라커</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_tag\" style=\"margin-left: 5px;\">\r\n");
      out.write("							<label for=\"\" class=\"filter_shower filter\">#샤워실</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_tag\" style=\"margin-left: 5px;\">\r\n");
      out.write("							<label for=\"\" class=\"filter_park filter\">#주차장</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("				<script>\r\n");
      out.write("					$(\"#searchInput\").on(\"keyup\", function(e){\r\n");
      out.write("						if(e.keyCode == 13) {\r\n");
      out.write("							$(\"#subForm\").submit();\r\n");
      out.write("						};\r\n");
      out.write("					});\r\n");
      out.write("				</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		var markers = [];\r\n");
      out.write("	\r\n");
      out.write("		var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("		    mapOption = {\r\n");
      out.write("		        center: new kakao.maps.LatLng(37.56793539931502, 126.98309190765903), // 지도의 중심좌표\r\n");
      out.write("		        level: 3 // 지도의 확대 레벨\r\n");
      out.write("		    };  \r\n");
      out.write("	\r\n");
      out.write("		// 지도를 생성합니다    \r\n");
      out.write("		var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("		\r\n");
      out.write("		// 일반 지도와 스카이뷰로 지도 타입을 전환할 수 있는 지도타입 컨트롤을 생성합니다\r\n");
      out.write("        var mapTypeControl = new kakao.maps.MapTypeControl();\r\n");
      out.write("        // 지도 확대 축소를 제어할 수 있는  줌 컨트롤을 생성합니다\r\n");
      out.write("        var zoomControl = new kakao.maps.ZoomControl();\r\n");
      out.write("        map.addControl(zoomControl, kakao.maps.ControlPosition.BOTTOMLEFT);\r\n");
      out.write("        // 지도에 컨트롤을 추가해야 지도위에 표시됩니다\r\n");
      out.write("        // kakao.maps.ControlPosition은 컨트롤이 표시될 위치를 정의하는데 TOPRIGHT는 오른쪽 위를 의미합니다\r\n");
      out.write("        map.addControl(mapTypeControl, kakao.maps.ControlPosition.BOTTOMLEFT);\r\n");
      out.write("        \r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("		\r\n");
      out.write("		function createMarker(name, x, y){\r\n");
      out.write("			var positions =\r\n");
      out.write("				{\r\n");
      out.write("					content: \"<div class=info><img src='/resource/duck.ico'>\"+name+\"</div>\", \r\n");
      out.write("					latlng: new kakao.maps.LatLng(x, y)\r\n");
      out.write("				}\r\n");
      out.write("			\r\n");
      out.write("			// 마커 이미지의 이미지 주소입니다\r\n");
      out.write("			var imageSrc = \"/resource/ping.png\"; \r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				// 마커 이미지의 이미지 크기 입니다\r\n");
      out.write("				var imageSize = new kakao.maps.Size(64, 69);\r\n");
      out.write("				\r\n");
      out.write("				// 마커 이미지를 생성합니다    \r\n");
      out.write("				var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);\r\n");
      out.write("				\r\n");
      out.write("				// 마커를 생성합니다\r\n");
      out.write("				var marker = new kakao.maps.Marker({\r\n");
      out.write("					map: map, // 마커를 표시할 지도\r\n");
      out.write("					position: positions.latlng, // 마커를 표시할 위치\r\n");
      out.write("					image : markerImage // 마커 이미지 \r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				// 마커에 표시할 인포윈도우를 생성합니다 \r\n");
      out.write("				var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("					content: positions.content // 인포윈도우에 표시할 내용\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				// 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다\r\n");
      out.write("				// 이벤트 리스너로는 클로저를 만들어 등록합니다 \r\n");
      out.write("				// for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다\r\n");
      out.write("				kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));\r\n");
      out.write("				kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));\r\n");
      out.write("\r\n");
      out.write("				// 마커 클릭 시 해당 리스트로 focus\r\n");
      out.write("				kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("					let target = $(\".gym_list_name[value='\"+ name + \"']\").closest(\".gym_list\");\r\n");
      out.write("				});\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		// 인포윈도우를 표시하는 클로저를 만드는 함수입니다 \r\n");
      out.write("		function makeOverListener(map, marker, infowindow) {\r\n");
      out.write("			return function() {\r\n");
      out.write("				infowindow.open(map, marker);\r\n");
      out.write("			};\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 인포윈도우를 닫는 클로저를 만드는 함수입니다 \r\n");
      out.write("		function makeOutListener(infowindow) {\r\n");
      out.write("			return function() {\r\n");
      out.write("				infowindow.close();\r\n");
      out.write("			};\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		$(\".gym_list\").on(\"click\", e => { \r\n");
      out.write("			panTo(e);\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 지도 이동 함수\r\n");
      out.write("		function panTo(e) {\r\n");
      out.write("			// 이동할 위도 경도 위치를 생성합니다 \r\n");
      out.write("			let x = $(e.target).closest(\".gym_list\").find(\".gym_list_x\").val();\r\n");
      out.write("			let y = $(e.target).closest(\".gym_list\").find(\".gym_list_y\").val();\r\n");
      out.write("			var moveLatLon = new kakao.maps.LatLng(x, y);\r\n");
      out.write("			\r\n");
      out.write("			// 지도 중심을 부드럽게 이동시킵니다\r\n");
      out.write("			// 만약 이동할 거리가 지도 화면보다 크면 부드러운 효과 없이 이동합니다\r\n");
      out.write("			map.panTo(moveLatLon);            \r\n");
      out.write("		}       \r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /layout/header.jsp(120,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userSeq != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" onclick=\"$.get('/logout.user').done(() => { location.reload() });\">로그아웃</a>\r\n");
          out.write("								</li>\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" href=\"/page.userMyPage\">마이페이지</a>\r\n");
          out.write("								</li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /layout/header.jsp(128,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bsSeq != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" onclick=\"$.get('/logout.user').done(() => { location.reload() });\">로그아웃</a>\r\n");
          out.write("								</li>\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" href=\"/page.bsPage\">사업자페이지</a>\r\n");
          out.write("								</li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /layout/header.jsp(136,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" onclick=\"$.get('/logout.user').done(() => { location.reload() });\">로그아웃</a>\r\n");
          out.write("								</li>\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" href=\"/userslist.host\">관리자페이지</a>\r\n");
          out.write("								</li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\"onclick=\"showLoginModal()\">로그인</a>\r\n");
          out.write("								</li>\r\n");
          out.write("								<li class=\"float-end\">\r\n");
          out.write("									<a class=\"header_a_tag\" onclick=\"showSignupModal()\">회원가입</a>\r\n");
          out.write("								</li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /gym/search.jsp(76,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("gymList");
      // /gym/search.jsp(76,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/gym/search.jsp(76,4) '${gymList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${gymList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<div class=\"gym_list\">\r\n");
            out.write("						<div class=\"gym_list_logo\">\r\n");
            out.write("							<img\r\n");
            out.write("								src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSk-2OF05AQfP8ncj64XfrCoQ3TNBJ-r0xjzQ&usqp=CAU\">\r\n");
            out.write("						</div>\r\n");
            out.write("						<div class=\"gym_list_article\">\r\n");
            out.write("							<div class=\"gym_list_title\">\r\n");
            out.write("								<a href=\"/detail.gym?gym_seq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"gym_list_location\">\r\n");
            out.write("								<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_location }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"gym_list_phone\">\r\n");
            out.write("								<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"gym_list_open\">\r\n");
            out.write("								<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_open }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('/');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_close }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"gym_list_tagBox\">\r\n");
            out.write("								<div class=\"gym_list_tag open btn_base\">#24시간</div>\r\n");
            out.write("								<div class=\"gym_list_tag locker btn_base\">#라커</div>\r\n");
            out.write("								<div class=\"gym_list_tag shower btn_base\">#샤워실</div>\r\n");
            out.write("								<div class=\"gym_list_tag park btn_base\">#주차장</div>\r\n");
            out.write("								<input type=\"hidden\" class=\"gym_list_x\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_x}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								<input type=\"hidden\" class=\"gym_list_y\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_y}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								<input type=\"hidden\" class=\"gym_list_name\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>				\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /gym/search.jsp(209,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("gymList");
      // /gym/search.jsp(209,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/gym/search.jsp(209,1) '${gymList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${gymList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<script>\r\n");
            out.write("			createMarker(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(',');
            out.write('"');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_x}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(',');
            out.write('"');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gymList.gym_y}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\");\r\n");
            out.write("		</script>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
