/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-11-22 00:23:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/user/login.jsp", Long.valueOf(1668351932955L));
    _jspx_dependants.put("/layout/footer.jsp", Long.valueOf(1668597354132L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/Documents/develop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH-semi-project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667273598260L));
    _jspx_dependants.put("/layout/header.jsp", Long.valueOf(1668601085670L));
    _jspx_dependants.put("/user/signup.jsp", Long.valueOf(1668597354134L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>피트니즈 - Fitneeds</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resource/fitneeds.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"\r\n");
      out.write("            integrity=\"sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- google font -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Pretendard font -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("          href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap - css -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("          integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("            integrity=\"sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8\"\r\n");
      out.write("            crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap - icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Fontawesome - icon  -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Daum zipcode -->\r\n");
      out.write("    <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("    <!-- Kakaomaps - ykm -->\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("            src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=b70a07e8ebffe5918d15f49ba310485f&libraries=services\"></script>\r\n");
      out.write("    <!-- Kakaomaps - kms -->\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("            src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=12fd95dff1fb7039a62aa4e24d3011f0&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- AOS -->\r\n");
      out.write("    <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Owl carousel -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- sweetalert -->\r\n");
      out.write("    <script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--  calendar -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/api/jquery-ui/jquery-ui.css\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Chart -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/base.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/index.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/search.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/gym-detail.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/users-mypage.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/users.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/bs.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/bs-page.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/personal-record.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/review.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/gym-modify.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Site header -->\r\n");
      out.write("<header id=\"header\" seq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userSeq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("    <div class=\"containerbox\" style=\"position:absolute; left:50%; transform: translate(-50%, 0);\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"float-start\">\r\n");
      out.write("            <a class=\"header_a_tag\" href=\"/\"><h1 id=\"header_logo\">Fitneeds</h1></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"float-start\">\r\n");
      out.write("            <nav id=\"header_nav_text\">\r\n");
      out.write("                <ul id=\"header_nav_menu\">\r\n");
      out.write("                    <li class=\"float-start\"><a class=\"header_a_tag\" href=\"/main.search\">헬스장검색</a></li>\r\n");
      out.write("                    <!--<li class=\"float-start\"><a class=\"header_a_tag\" href=\"#\">실시간리뷰</a></li>-->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul id=\"header_nav_person\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"loginModal\" class=\"loginModal-overlay\" align=\"center\">\r\n");
      out.write("	<div class=\"window\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-12 text-end close-area\" onclick=hideLoginModal()>\r\n");
      out.write("			<a><i class=\"fa-solid fa-x\" style=\"color: #808080\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"text_title title\">회원 로그인</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 폼 -->\r\n");
      out.write("		<form id=\"form_login\">\r\n");
      out.write("			<div class=\"row justify-content-center mt-3\">\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">이메일</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"login_id\" id=\"login_id\"\r\n");
      out.write("						placeholder=\"이메일을 입력하세요.\" maxlength=\"40\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">비밀번호</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"login_pw\" id=\"login_pw\"\r\n");
      out.write("						placeholder=\"비밀번호를 입력하세요.\" maxlength=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<button type=\"button\" class=\"btn_base\" id=\"btn_login\">로그인</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-1\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"checkbox-bsLogin\">\r\n");
      out.write("						<label class=\"form-check-label\" for=\"login_bs\" style=\"color: #404040; font-size: 14px; letter-spacing: -1px;\">\r\n");
      out.write("							<input class=\"form-check-input\" type=\"checkbox\" id=\"login_bs\">\r\n");
      out.write("							<span class=\"checkbox__label\"></span>\r\n");
      out.write("							사업자 로그인</label>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-4\" style=\"letter-spacing: -1px;\">\r\n");
      out.write("					<span style=\"color: #404040;\">계정이 없으신가요?</span> <a href=\"#\"\r\n");
      out.write("						onclick=\"showSignupModal(); return false;\">회원가입</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-1\"\r\n");
      out.write("					style=\"color: #808080; font-size: small; letter-spacing: -1px;\">\r\n");
      out.write("					<a onclick=\"showSearchPw()\">비밀번호를 잊으셨나요?</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- 비밀번호 찾기 폼 -->\r\n");
      out.write("		<form class=\"search\" id=\"form_searchPw\">\r\n");
      out.write("			<div class=\"row justify-content-center mt-4\">\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<input type=\"text\" name=\"email\" id=\"searchPw_email\"\r\n");
      out.write("						placeholder=\"이메일\" maxlength=\"40\">\r\n");
      out.write("					<div class=\"text-start mt-1 mb-1\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">회원 가입시 사용한\r\n");
      out.write("							이메일을 입력하세요.</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<input type=\"text\" name=\"phone\" id=\"searchPw_phone\"\r\n");
      out.write("						placeholder=\"핸드폰 번호\" maxlength=\"14\" oninput=\"validNum()\">\r\n");
      out.write("					<div class=\"text-start mt-1 mb-1\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">회원 가입시 사용한\r\n");
      out.write("							핸드폰 번호를 입력하세요.</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<button class=\"btn_base\" type=\"button\" id=\"btn_search\">찾기</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-1\">\r\n");
      out.write("					<div class=\"checkbox-bsLogin\">\r\n");
      out.write("						<label class=\"form-check-label\" for=\"searchPw_bs\" style=\"color: #404040; font-size: 14px; letter-spacing: -1px;\">\r\n");
      out.write("						<input class=\"form-check-input\" type=\"checkbox\" id=\"searchPw_bs\">\r\n");
      out.write("						<span class=\"checkbox__label\"></span>\r\n");
      out.write("							사업자 입니다.</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<a style=\"color: #808080\" onclick=\"toBackward()\">Back</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("			// 로그인 loginModal 열기\r\n");
      out.write("			function showLoginModal() {\r\n");
      out.write("				$(\"#loginModal\").attr(\"style\", \"display:inline-flex\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 로그인 loginModal 닫기\r\n");
      out.write("			function hideLoginModal() {\r\n");
      out.write("				$(\"#loginModal\").attr(\"style\", \"display:none\");\r\n");
      out.write("				toBackward();\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 비밀번호 찾기 페이지 처리\r\n");
      out.write("			function showSearchPw() {\r\n");
      out.write("				$(\"#form_login\").attr(\"style\", \"display:none\");\r\n");
      out.write("				$(\"#form_searchPw\").attr(\"style\", \"display:inline\");\r\n");
      out.write("				$(\"#loginModal .title\").text(\"비밀번호 찾기\");\r\n");
      out.write("				$(\"#loginModal .window\").attr(\"style\", \"height:450px\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 뒤로가기 처리\r\n");
      out.write("			function toBackward() {\r\n");
      out.write("				$(\".search\").attr(\"style\", \"display:none\");\r\n");
      out.write("				$(\"#loginModal input:not([type='checkbox']\").val(\"\");\r\n");
      out.write("				$(\"#form_login\").attr(\"style\", \"display:inline\");\r\n");
      out.write("				$(\"#loginModal .title\").text(\"회원 로그인\");\r\n");
      out.write("				$(\"#loginModal .window\").attr(\"style\", \"height:475px\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 떨림 애니메이션\r\n");
      out.write("			function wobble(element) {\r\n");
      out.write("				let order = [0, -8, 8, -4, 4, -2, 2, -1, 1, 0];\r\n");
      out.write("				let seq = [];\r\n");
      out.write("				order.forEach(function (y) { seq.push({ transform: \"translate(0,\" + y + \"px)\" }); });\r\n");
      out.write("				element.animate(seq, { duration: 300 });\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 유효성 검사 (공백 확인)\r\n");
      out.write("			function isFilled(elements) {\r\n");
      out.write("				for (i = 0; i < elements.length; i++) {\r\n");
      out.write("					if(elements[i].value == \"\") { \r\n");
      out.write("						wobble(elements[i]);\r\n");
      out.write("						elements[i].focus();\r\n");
      out.write("						return false; \r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				return true;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 로그인 함수\r\n");
      out.write("			function tryLogin() {\r\n");
      out.write("				$.post($(\"#login_bs\").is(\":checked\") ? \"/login.bs\" : \"/login.user\", $(\"#form_login\").serialize())\r\n");
      out.write("					.done((res) => {\r\n");
      out.write("						if (res == \"true\") {\r\n");
      out.write("							Swal.fire({ title: \"Success!\", icon: \"success\", text: \"로그인에 성공했습니다.\" })\r\n");
      out.write("								.then((result) => {\r\n");
      out.write("									if (result.isConfirmed) {\r\n");
      out.write("										//사업자회원가입 후 index페이지 열기\r\n");
      out.write("										if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start!=null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('|');
      out.write('|');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start!=undefind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("											if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start == \"login\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("												location.href= \"/\";\r\n");
      out.write("											}\r\n");
      out.write("										} else {\r\n");
      out.write("											location.reload();\r\n");
      out.write("										}\r\n");
      out.write("									}\r\n");
      out.write("								});\r\n");
      out.write("						} else {\r\n");
      out.write("							Swal.fire({ title: \"Error\", icon: \"error\", text: \"ID가 등록되지 않았거나 비밀번호가 올바르지 않습니다.\" });\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 비밀번호 찾기 함수\r\n");
      out.write("			function trySearchPw() {\r\n");
      out.write("				$.get($(\"#searchPw_bs\").is(\":checked\") ? \"/searchPw.bs\" : \"/searchPw.user\", $(\"#form_searchPw\").serialize())\r\n");
      out.write("				.done((res => {\r\n");
      out.write("						if (res == \"true\") {\r\n");
      out.write("							// Fake Alert\r\n");
      out.write("							Swal.fire({ title: \"Success!\", icon: \"success\", html: \"등록된 이메일 주소로<br>비밀번호 설정 링크가 발송되었습니다.<br>\" })\r\n");
      out.write("						} else {	\r\n");
      out.write("							Swal.fire({ title: \"Error\", icon: \"error\", text: \"등록된 가입 정보가 없습니다.\" });\r\n");
      out.write("						}\r\n");
      out.write("					}));\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// ESC 누르면 Modal 닫기\r\n");
      out.write("			$(window).on(\"keyup\", e => {\r\n");
      out.write("				if ($(\"#loginModal\")[0].style.display == \"inline-flex\" && e.keyCode == 27) { hideLoginModal(); }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 창 바깥쪽 클릭하면 Modal 닫기\r\n");
      out.write("			// $(\"#loginModal\").on(\"click\", e => {\r\n");
      out.write("			// 	if (e.target.classList.contains(\"loginModal-overlay\")) { hideLoginModal(); }\r\n");
      out.write("			// });\r\n");
      out.write("\r\n");
      out.write("			// 버튼 이벤트\r\n");
      out.write("			$(\"#btn_login\").on(\"click\", () => {\r\n");
      out.write("				if (isFilled($(\"#login_id, #login_pw\"))) { tryLogin(); }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#btn_search\").on(\"click\", () => {\r\n");
      out.write("				if (isFilled($(\"#searchPw_email, #searchPw_phone\"))) { trySearchPw(); }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 엔터 = 버튼 클릭\r\n");
      out.write("			$(\"#login_id, #login_pw\").on(\"keyup\", (e) => { if (e.keyCode == 13) { $(\"#btn_login\").click() } });\r\n");
      out.write("			$(\"#searchPw_email, #searchPw_phone\").on(\"keyup\", (e) => { if (e.keyCode == 13) { $(\"#btn_search\").click() } });;\r\n");
      out.write("		</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"signupModal\" class=\"signupModal-overlay\" align=\"center\">\r\n");
      out.write("	<div class=\"window\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-12 text-end close-area\" onclick=hideSignupModal()>\r\n");
      out.write("			<a><i class=\"fa-solid fa-x\" style=\"color: #808080\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"text_title title\">일반 회원가입</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 회원가입 폼 -->\r\n");
      out.write("		<form id=\"form_sign\" method=\"post\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-3\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">이메일</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"users_email\" id=\"users_email\"\r\n");
      out.write("						placeholder=\"이메일을 입력하세요.\" maxlength=\"25\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-2\">\r\n");
      out.write("					<div class=\"error_msg text_mini text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span class=\"error_msg_display\" id=\"users_email_msg\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">비밀번호</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"users_pw\" id=\"users_pw\"\r\n");
      out.write("						placeholder=\"비밀번호를 입력하세요.\" maxlength=\"16\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">비밀번호 확인</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"users_pw_re\" id=\"users_pw_re\"\r\n");
      out.write("						placeholder=\"동일 비밀번호를 입력하세요.\" maxlength=\"16\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-2\">\r\n");
      out.write("					<div class=\"error_msg text_mini text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span class=\"error_msg_display\" id=\"users_pw_re_msg\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<div class=\"text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span style=\"color: #808080; font-size: x-small\">연락처</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"users_phone\" id=\"users_phone\"\r\n");
      out.write("						placeholder=\"연락처를 입력하세요.\" maxlength=\"11\" oninput=validNum()>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-2\">\r\n");
      out.write("					<div class=\"error_msg text_mini text-start\" style=\"width: 250px\">\r\n");
      out.write("						<span class=\"error_msg_display\" id=\"users_phone_msg\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 gy-4\">\r\n");
      out.write("					<button type=\"button\" class=\"btn_base\" id=\"btn_sign\">회원가입</button>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 gy-3\"\r\n");
      out.write("					style=\"font-size: small; letter-spacing: -1px;\">\r\n");
      out.write("					<span style=\"color: #808080;\">시설운영자로 가입하길 원하시나요?</span><br> <a\r\n");
      out.write("						href=\"/sign.bs\">사업자회원가입</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("        // 회원가입 signupModal 열기\r\n");
      out.write("        function showSignupModal() {\r\n");
      out.write("            $(\"#signupModal\").attr(\"style\", \"display:inline-flex\");\r\n");
      out.write("            $(\"#loginModal\").attr(\"style\", \"display:none\");\r\n");
      out.write("            toBackward();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("     	// 회원가입 signupModal 닫기\r\n");
      out.write("		function hideSignupModal() {\r\n");
      out.write("			$(\"#signupModal\").attr(\"style\", \"display:none\");\r\n");
      out.write("			\r\n");
      out.write("        	$(\"#users_email\").val(\"\");\r\n");
      out.write("        	$(\"#users_pw\").val(\"\");\r\n");
      out.write("        	$(\"#users_pw_re\").val(\"\");\r\n");
      out.write("        	$(\"#users_phone\").val(\"\");\r\n");
      out.write("        	\r\n");
      out.write("        	$(\"#users_email_msg\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#users_email_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("            $(\"#users_email_msg\").html(\"이메일 형식을 아이디로 사용합니다\");\r\n");
      out.write("\r\n");
      out.write("            $(\"#users_pw_re_msg\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#users_pw_re_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("            $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("            \r\n");
      out.write("            $(\"#users_phone_msg\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#users_phone_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("            $(\"#users_phone_msg\").html(\"연락처는 - 를 제외한 숫자만 입력해주세요\");\r\n");
      out.write("		}\r\n");
      out.write("     	\r\n");
      out.write("        // ESC 누르면 signupModal 닫기\r\n");
      out.write("        $(window).on(\"keyup\", e => {\r\n");
      out.write("            if ($(\"#signupModal\")[0].style.display == \"inline-flex\" && e.keyCode == 27) { hideSignupModal(); }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //  회원가입 함수\r\n");
      out.write("        function trySign() {\r\n");
      out.write("        	$.post(\"/sign.user\", $(\"#form_sign\").serialize())\r\n");
      out.write("                .done((resp) => {\r\n");
      out.write("                	if (resp == \"1\") {\r\n");
      out.write("                        Swal.fire({ title: \"Success!\", icon: \"success\", text: \"회원가입이 되었습니다.\"})\r\n");
      out.write("                            .then((result) => {\r\n");
      out.write("                                if (result.isConfirmed) { location.reload(); }\r\n");
      out.write("                            });\r\n");
      out.write("                    } else {\r\n");
      out.write("                        Swal.fire({ title: \"Error\", icon: \"error\", text: \"오류입니다. 관리자에게 문의해주세요.\"});\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("             	            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 회원가입 버튼 이벤트\r\n");
      out.write("        $(\"#btn_sign\").on(\"click\", () => {\r\n");
      out.write("            \r\n");
      out.write("            if ($(\"#users_email_msg\").css(\"color\") == \"rgb(255, 0, 0)\") { wobble($(\"#users_email\")[0]); $(\"#users_email\").focus(); }\r\n");
      out.write("            \r\n");
      out.write("            else if ($(\"#users_pw_re_msg\").css(\"color\") == \"rgb(255, 0, 0)\") {\r\n");
      out.write("                if ($(\"#users_pw_re_msg\").html() == \"특수문자를 포함한 8~16자리 입력해주세요\") { wobble($(\"#users_pw\")[0]); $(\"#users_pw\").focus(); }\r\n");
      out.write("                else if ($(\"#users_pw_re_msg\").html() == \"동일한 비밀번호를 입력해주세요\") { wobble($(\"#users_pw_re\")[0]); $(\"#users_pw_re\").focus(); }\r\n");
      out.write("            }\r\n");
      out.write("            else if ($(\"#users_phone_msg\").css(\"color\") == \"rgb(255, 0, 0)\") { \r\n");
      out.write("            	wobble($(\"#users_phone\")[0]); $(\"#users_phone\").focus();\r\n");
      out.write("            	\r\n");
      out.write("            } else {\r\n");
      out.write("            	if (isFilled($(\"#users_email, #users_pw, #users_pw_re, #users_phone\"))) { trySign(); }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 유효성 검사 Regex\r\n");
      out.write("        let emailRegex = /^[a-zA-Z0-9+-\\_.]{1,20}@[a-zA-Z0-9-]{1,15}\\.[a-zA-Z-.]{1,12}$/;\r\n");
      out.write("        let pwRegex = /^(?=.*[A-Za-z\\d])(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$/;\r\n");
      out.write("        let phoneRegex = /^0[\\d]{8,10}$/;\r\n");
      out.write("\r\n");
      out.write("        // input 칸에 숫자 외에 입력 안되게 막기\r\n");
      out.write("        function validNum() {\r\n");
      out.write("            event.target.value = event.target.value.replace(/[^0-9]/g, '').replace(/(\\..*)\\./g, '$1');\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("        // 이메일(아이디) - 아이디 중복검사 & 값 입력 유효성 검사 display\r\n");
      out.write("\r\n");
      out.write("        function idEvent() {\r\n");
      out.write("            if ($(\"#users_email\").val() == \"\") {\r\n");
      out.write("                $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_email_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                $(\"#users_email_msg\").html(\"이메일 형식을 아이디로 사용합니다\");\r\n");
      out.write("            } else if (!emailRegex.test($(\"#users_email\").val())) {\r\n");
      out.write("                $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_email_msg\").css(\"color\", \"red\");\r\n");
      out.write("                $(\"#users_email_msg\").html(\"이메일 형식을 확인해주세요\");\r\n");
      out.write("            } else {\r\n");
      out.write("            	let email = $(\"#users_email\").val();\r\n");
      out.write("            	\r\n");
      out.write("            	$.ajax({\r\n");
      out.write("                    url: \"/duplCheck.user\",\r\n");
      out.write("                    data: { \"users_email\": email }\r\n");
      out.write("                }).done(function (resp) {\r\n");
      out.write("                	\r\n");
      out.write("                    if (resp == \"true\") { // 아이디가 이미 존재하므로 사용할 수 없는 경우\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"color\", \"red\");\r\n");
      out.write("                        $(\"#users_email_msg\").html(\"이미 사용 중인 ID 입니다.\");\r\n");
      out.write("                    } else { // 아이디가 존재하지않으므로 사용할 수 있는 경우\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"display\", \"block\");\r\n");
      out.write("                        $(\"#users_email_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                        $(\"#users_email_msg\").html(\"사용 가능한 ID 입니다.\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        $(\"#users_email\").on(\"focus\", function () {\r\n");
      out.write("            idEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_email\").on(\"keyup\", function () {\r\n");
      out.write("            idEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 패스워드 - 값 입력 유효성 검사 display\r\n");
      out.write("\r\n");
      out.write("        function pwEvent() {\r\n");
      out.write("            if ($(\"#users_pw, #users_pw_re\").val() == \"\") {\r\n");
      out.write("                $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_pw_re_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("\r\n");
      out.write("                if (!pwRegex.test($(\"#users_pw\").val())) {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                } else if (($(\"#users_pw\").val() != $(\"#users_pw_re\").val()) && $(\"#users_pw, #users_pw_re\").val() != \"\") {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"동일한 비밀번호를 입력해주세요\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                } else if (($(\"#users_pw\").val() != $(\"#users_pw_re\").val()) && $(\"#users_pw, #users_pw_re\").val() == \"\") {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"위에 입력한 비밀번호와 일치하지않습니다\");\r\n");
      out.write("\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"display\", \"none\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                    $(\"#users_pw_re_msg\").html(\"특수문자를 포함한 8~16자리 입력해주세요\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_pw, #users_pw_re\").on(\"focus\", function () {\r\n");
      out.write("            pwEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_pw, #users_pw_re\").on(\"keyup\", function () {\r\n");
      out.write("            pwEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 전화번호 - 값 입력 유효성 검사 display\r\n");
      out.write("\r\n");
      out.write("        function phoneEvent() {\r\n");
      out.write("            if ($(\"#users_phone\").val() == \"\") {\r\n");
      out.write("                $(\"#users_phone_msg\").css(\"display\", \"block\");\r\n");
      out.write("                $(\"#users_phone_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                $(\"#users_phone_msg\").html(\"연락처는 - 를 제외한 숫자만 입력해주세요\");\r\n");
      out.write("            } else {\r\n");
      out.write("            	if (!phoneRegex.test($(\"#users_phone\").val())) {\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"color\", \"red\");\r\n");
      out.write("                    $(\"#users_phone_msg\").html(\"옳바른 번호 형식을 입력해주세요\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"display\", \"none\");\r\n");
      out.write("                    $(\"#users_phone_msg\").css(\"color\", \"#001A41\");\r\n");
      out.write("                    $(\"#users_phone_msg\").html(\"연락처는 - 를 제외한 숫자만 입력해주세요\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_phone\").on(\"focus\", function () {\r\n");
      out.write("            phoneEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#users_phone\").on(\"keyup\", function () {\r\n");
      out.write("            phoneEvent();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 엔터 = 버튼 클릭\r\n");
      out.write("        $(\"#users_email, #users_pw, #users_pw_re, #users_phone\").on(\"keyup\", (e) => { if (e.keyCode == 13) { $(\"#btn_sign\").click() } });\r\n");
      out.write("\r\n");
      out.write("    </script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start!=null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('|');
      out.write('|');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start!=undefind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("        //사업자회원가입 후 index에서 로그인 Modal 열기\r\n");
      out.write("        if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start == \"login\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("            $(\"#loginModal\").attr(\"style\", \"display:inline-flex\");\r\n");
      out.write("            $(\"#login_bs\").attr(\"checked\", true);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function getDateFormat(date) {\r\n");
      out.write("        let month = date.getMonth() + 1;\r\n");
      out.write("        let day = date.getDate();\r\n");
      out.write("        let hour = date.getHours();\r\n");
      out.write("        let minute = date.getMinutes();\r\n");
      out.write("        let second = date.getSeconds();\r\n");
      out.write("\r\n");
      out.write("        month = month >= 10 ? month : '0' + month;\r\n");
      out.write("        day = day >= 10 ? day : '0' + day;\r\n");
      out.write("        hour = hour >= 10 ? hour : '0' + hour;\r\n");
      out.write("        minute = minute >= 10 ? minute : '0' + minute;\r\n");
      out.write("        second = second >= 10 ? second : '0' + second;\r\n");
      out.write("\r\n");
      out.write("        return date.getFullYear() + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>history.scrollRestoration = \"manual\"</script>\r\n");





      out.write("\r\n");
      out.write("			<!-- Site Main -->\r\n");
      out.write("			<main id=\"index\">\r\n");
      out.write("				<section>\r\n");
      out.write("					<form action=\"/gym.search\" id=\"form_search\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"wrap\">\r\n");
      out.write("							<div class=\"mainimg bg type-b\"></div>\r\n");
      out.write("							<div class=\"containerbox\">\r\n");
      out.write("								<div class=\"search_main\" data-aos=\"zoom-out\" data-aos-easing=\"linear\"\r\n");
      out.write("									data-aos-duration=\"1000\">\r\n");
      out.write("									<div class=\"search_main_span\">\r\n");
      out.write("										<span style=\"font-weight: lighter;\">Your</span> <span\r\n");
      out.write("											style=\"font-weight: bold;\">Needs</span> <span\r\n");
      out.write("											style=\"font-weight: lighter;\">For</span> <span\r\n");
      out.write("											style=\"font-weight: bold;\">Fitness</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"search_main_input\">\r\n");
      out.write("										<input type=\"text\" placeholder=\"지역명 또는 헬스장명을 검색해보세요.\" style=\"padding-left: 20px\"\r\n");
      out.write("											name=\"searchInput\" maxlength=\"20\">\r\n");
      out.write("										<input type=\"hidden\" value=\"false\" name=\"open_result\">\r\n");
      out.write("										<input type=\"hidden\" value=\"false\" name=\"locker_result\">\r\n");
      out.write("										<input type=\"hidden\" value=\"false\" name=\"shower_result\">\r\n");
      out.write("										<input type=\"hidden\" value=\"false\" name=\"park_result\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<i class=\"fa-solid fa-magnifying-glass\" id=\"btn_search\" onclick=\"$('#form_search').submit();\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"containerbox\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Review Carousel -->\r\n");
      out.write("					<section class=\"row justify-content-center review\">\r\n");
      out.write("						<h2 class=\"text-center col-12 mt-5 mb-5\">Best User Reviews</h2>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-12 carousel\">\r\n");
      out.write("							<div class=\"prevBox\">\r\n");
      out.write("								<i class=\"fa-solid fa-angle-left angle\" onclick=\"owl.trigger('prev.owl.carousel', [2000]);\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"owl-carousel text-center\" style=\"width: 1050px; height: 400px\">\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"nextBox\">\r\n");
      out.write("								<i class=\"fa-solid fa-angle-right angle\" onclick=\"owl.trigger('next.owl.carousel', [2000]);\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<!-- Image Section -->\r\n");
      out.write("					<section class=\"row justify-content-evenly preview mb-5\">\r\n");
      out.write("						<h2 class=\"text-center col-12 mt-5 mb-5\">Image Preview</h2>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-4 imgBox\">\r\n");
      out.write("							<div class=\"imgFilter\">\r\n");
      out.write("								<p></p>\r\n");
      out.write("								<input type=\"hidden\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/resource/img/health.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-4 imgBox\">\r\n");
      out.write("							<div class=\"imgFilter\">\r\n");
      out.write("								<p></p>\r\n");
      out.write("								<input type=\"hidden\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/resource/img/health.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-4 imgBox\">\r\n");
      out.write("							<div class=\"imgFilter\">\r\n");
      out.write("								<p></p>\r\n");
      out.write("								<input type=\"hidden\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/resource/img/health.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-4 imgBox\">\r\n");
      out.write("							<div class=\"imgFilter\">\r\n");
      out.write("								<p></p>\r\n");
      out.write("								<input type=\"hidden\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/resource/img/health.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-4 imgBox\">\r\n");
      out.write("							<div class=\"imgFilter\">\r\n");
      out.write("								<p></p>\r\n");
      out.write("								<input type=\"hidden\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/resource/img/health.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-4 imgBox\">\r\n");
      out.write("							<div class=\"imgFilter\">\r\n");
      out.write("								<p></p>\r\n");
      out.write("								<input type=\"hidden\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<img src=\"/resource/img/health.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<!-- Banner Section -->\r\n");
      out.write("					<section class=\"row justify-content-evenly ads mb-5\">\r\n");
      out.write("						<h2 class=\"text-center col-12 mt-5 mb-5\">Recommended Items</h2>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6\">\r\n");
      out.write("							<div class=\"banner\"><img src=\"/resource/img/banner_img1.jpg\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-6\">\r\n");
      out.write("							<div class=\"banner\"><img src=\"/resource/img/banner_img2.jpg\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-6 gy-5\">\r\n");
      out.write("							<div class=\"banner\"><img src=\"/resource/img/banner_img3.jpg\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-6 gy-5\">\r\n");
      out.write("							<div class=\"banner\"><img src=\"/resource/img/banner_img4.jpg\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-5 mb-5\"></div>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("			</main>\r\n");
      out.write("			<script>\r\n");
      out.write("				\r\n");
      out.write("				$(() => {\r\n");
      out.write("					getReviewData();\r\n");
      out.write("					getGymData();\r\n");
      out.write("					$('.owl-carousel').trigger('next.owl.carousel', [10000]);\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				// AOS 스크립트 시작\r\n");
      out.write("				AOS.init(); // 자바스크립트로 init()을 해야 동작한다.\r\n");
      out.write("\r\n");
      out.write("				// Review DB 가져온 뒤 Carousel 연결 함수\r\n");
      out.write("				function getReviewData() {\r\n");
      out.write("					$.getJSON(\"/review.index\", res => {\r\n");
      out.write("						let item_list = document.querySelectorAll(\".item\");\r\n");
      out.write("						for (i = 0; i < item_list.length / 2; i++) {\r\n");
      out.write("							let review = reviewBuilder(res.reviewList[i]);\r\n");
      out.write("							item_list[i].innerHTML = review;\r\n");
      out.write("							item_list[i + 10].innerHTML = review;\r\n");
      out.write("							$(item_list[i]).find(\".item_title>a\")[0].innerText = res.reviewList[i].gym.gym_name;\r\n");
      out.write("							$(item_list[i+ 10]).find(\".item_title>a\")[0].innerText = res.reviewList[i].gym.gym_name;\r\n");
      out.write("							$(item_list[i]).find(\".item_contents\")[0].innerText = res.reviewList[i].review.review_contents;\r\n");
      out.write("							$(item_list[i+ 10]).find(\".item_contents\")[0].innerText = res.reviewList[i].review.review_contents;\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				// Review 폼 구성 함수\r\n");
      out.write("				function reviewBuilder(data) {\r\n");
      out.write("					let gymName = \"<div class='col-12 text_title_600 text-truncate item_title'><a href='/detail.gym?gym_seq=\" + data.gym.gym_seq + \"'></a></div>\";\r\n");
      out.write("					let star = \"\";\r\n");
      out.write("					for (j = 1; j < 6; j++) {star += j <= data.review.review_star ? \"<label class='item_filledStar'>★</label>\" : \"<label class='item_emptyStar'>★</label>\";}\r\n");
      out.write("					let score = \"<div class='col-12 gy-2' align=center>\" + star + \"</div>\";\r\n");
      out.write("					let space = \"<div class='col-1 gy-3'></div><hr class='col-10 gy-3'><div class='col-1 gy-3'></div>\";\r\n");
      out.write("					let certified = data.review.review_photo == \"인증완료\" ? \"<img src='/resource/fitneeds.ico' style='display:inline-block; width:20px'> \" : \" \"\r\n");
      out.write("					let writer = \"<div class='col-6 text-start text-truncate item_writer' style='padding-left:15px'>\" + certified + data.review.review_writer + \"</div>\";\r\n");
      out.write("					let writeDate = \"<div class='col-6 text_mini text-end text item_date' style='color:#808080; padding-right:15px'>\" + getDateFormat(new Date(data.review.review_writer_date)).slice(0, -3) + \"</div>\";\r\n");
      out.write("					let likes = \"<div class='col-6'></div><div class='col-6 text_mini text-end item_likes' style='color:#808080; padding-right:15px'>추천수 : \" + data.review.review_like + \"</div>\";\r\n");
      out.write("					let contents = \"<div class='col-12 gy-3 item_contents'></div>\";\r\n");
      out.write("					let medal = \"<img src='resource/img/medal.png' class='item_medal'>\"\r\n");
      out.write("					let result = \"<div class='row'>\" + gymName + score + space + writer + writeDate + likes + contents + \"</div>\" + medal;\r\n");
      out.write("					return result;\r\n");
      out.write("					// 오리 아이콘 <img src='/resource/duck.ico' style='display:inline-block; width:20px'>&nbsp\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				// Carousel 스크립트\r\n");
      out.write("				let owl = $('.owl-carousel');\r\n");
      out.write("				owl.owlCarousel({\r\n");
      out.write("					items: 3,\r\n");
      out.write("					startPosition: 3,\r\n");
      out.write("					margin: 50,\r\n");
      out.write("					loop: true,\r\n");
      out.write("					dots: false,\r\n");
      out.write("					autoplay: true,\r\n");
      out.write("					autoplaySpeed: 10000,\r\n");
      out.write("					autoplayTimeout: 10000,\r\n");
      out.write("					autoplayHoverPause: false\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				function getGymData() {\r\n");
      out.write("					$.getJSON(\"/gym.index\", res => {\r\n");
      out.write("						let item_list = document.querySelectorAll(\".imgBox\");\r\n");
      out.write("						for (i = 0; i < res.gymList.length; i++) {\r\n");
      out.write("							let item = item_list[i];\r\n");
      out.write("							let data = res.gymList[i];\r\n");
      out.write("							$(item).find(\".imgFilter>p\").html(data.gym.gym_name + \"<br>💕&nbsp\" + data.favorites.count).attr(\"seq\", data.gym.gym_seq);\r\n");
      out.write("							$(item).find(\".imgFilter\").attr(\"seq\", data.gym.gym_seq);\r\n");
      out.write("							if (data.gym.gym_main_sysImg != undefined) {\r\n");
      out.write("								$(item).find(\"img\").attr(\"src\", \"/resource/gym/\" + data.gym.gym_main_sysImg);\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				$(\".imgBox\").on(\"click\", e => {\r\n");
      out.write("					location.href = \"/detail.gym?gym_seq=\" + e.target.getAttribute(\"seq\");\r\n");
      out.write("				});\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Site footer -->\r\n");
      out.write("    <footer id=\"footer\">\r\n");
      out.write("        <div class=\"footer_line\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"containerbox\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"leftbox float-start\">\r\n");
      out.write("                <a class=\"footer_a_tag\" href=\"/\"><h2 id=\"footer_logo\">Fitneeds</h2></a>\r\n");
      out.write("                <h6 id=\"footer_contact\" class=\"text_mini\">제휴 및 서비스 이용문의</h6>\r\n");
      out.write("                <h3 id=\"footer_call\"><a class=\"footer_a_tag\" href=\"tel:1577-1000\">1577-1000</a></h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"rightbox float-start\">\r\n");
      out.write("                    <ul class=\"d-flex flex-row text_normal footer_list\">\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\">이용약관</a><span class=\"linetext\">&nbsp|&nbsp</span></li>\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\">개인정보처리방침</a><span class=\"linetext\">&nbsp|&nbsp</span></li>\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\">사이트맵</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"d-flex flex-row-reverse text_normal footer_sns\">\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a></li>\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\"><i class=\"fa-brands fa-twitter\"></i></a></li>\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a></li>\r\n");
      out.write("                        <li><a class=\"footer_a_tag\" href=\"#\"><i class=\"fa-brands fa-youtube\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"text_mini footer_infotext\">\r\n");
      out.write("                    <p>서울특별시 중구 남대문로 120 대일빌딩 2F, 3F<br>\r\n");
      out.write("                    대표 : 조성태<br>\r\n");
      out.write("                    사업자번호 : 851-87-00622<br>\r\n");
      out.write("                    통신판매번호 : 서울 강남 제2014-01호<br>\r\n");
      out.write("                    admin@fitneeds.shop</p>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"copyright-text\">Copyright ⓒ Fitneeds Co., Ltd. All rights reserved.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /layout/header.jsp(103,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!admin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li class=\"float-start\"><a class=\"header_a_tag\" href=\"/main.personal\">운동기록</a></li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /layout/header.jsp(110,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userSeq != null && userSeq!='99999'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\"\r\n");
          out.write("                                   onclick=\"$.get('/logout.user').done(() => { location.href='/' });\">로그아웃</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\" href=\"/page.userMyPage\">마이페이지</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /layout/header.jsp(119,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bsSeq != null && bsSeq!='99999'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\"\r\n");
          out.write("                                   onclick=\"$.get('/logout.user').done(() => { location.href='/' });\">로그아웃</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\" href=\"/page.bsPage\">사업자페이지</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /layout/header.jsp(128,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin || userSeq=='99999' || bsSeq=='99999'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\"\r\n");
          out.write("                                   onclick=\"$.get('/logout.user').done(() => { location.href='/' });\">로그아웃</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\" href=\"/admin.host\">관리자페이지</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\" onclick=\"showLoginModal()\">로그인</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                            <li class=\"float-end\">\r\n");
          out.write("                                <a class=\"header_a_tag\" onclick=\"showSignupModal()\">회원가입</a>\r\n");
          out.write("                            </li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
